### ISSUE TITLE
Backup doesn't work

### ISSUE THREAD

**Issue by guiadco** [actiniumio/allspark#103]
---
### Describe the bug

There is no downloads roles to use that vars
```image: "{{ downloads.volumerize.image }}:{{ downloads.volumerize.tag }}"```

No application found because the label is heritage not managedby
```shell: docker ps -q --filter label=managedby=allspark | xargs -n 1 docker inspect --format \{\{' .Name '\}\} | sed 's/\// /' | tr -d '\r\n'```

When you change that you can launch the backup playbook but the backup folder is empty.

---
### Reproduction scenario

- launch the backup.yml
```ansible-playbook -i hosts backup.yml```

---
### Expected behaviour

have a full backup:
```
-rw------- 1 root root 209690599 Sep 17 23:50 duplicity-full.20180917T215001Z.vol1.difftar.gz
-rw------- 1 root root 209689092 Sep 17 23:50 duplicity-full.20180917T215001Z.vol2.difftar.gz
-rw------- 1 root root 209685599 Sep 17 23:50 duplicity-full.20180917T215001Z.vol3.difftar.gz
-rw------- 1 root root 209656537 Sep 17 23:50 duplicity-full.20180917T215001Z.vol4.difftar.gz
```

**Comment by guiadco** [comment]
Need to change -> 
[ ] add the downloads roles only to test if you have all same image as the original for the backup playbook
[ ] change the command part to use the name of the container as explain on the volumerize's README
[ ] change the label used to get docker container list

**Comment by Xide** [comment]
Does the backup/restore playbooks merged in #128 works for you ?

**Comment by guiadco** [comment]
Now it works

**Comment by guiadco** [comment]
Ok
