### ISSUE TITLE
Document VirtualEnv Requirement

### ISSUE THREAD

**Issue by guiadco** [actiniumio/allspark#39]
### Describe the bug

You can not launch the hot reload part to review your work while editing

### To Reproduce

> **note**: You might want to use the Vagrant environment to create a reproducible scenario triggering the bug.

```[root@localhost allspark]# make doc
Setting up docs virtual environment
/bin/sh: virtualenv: command not found
make: *** [doc] Error 127
```

### Expected behavior

Generate the virtualenv

### Allspark informations

- **Allspark**
  - *configuration*

``` 
N/A
```

- **Control machine**
  - *Operating system* : 
    ```Linux localhost.localdomain 4.17.9-1.el7.elrepo.x86_64 #1 SMP Sun Jul 22 11:57:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux  ```
  - *Ansible version* :
  
```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

  - *Vagrant version* (if used to reproduce the issue) : N/A
- **Allspark server**
  - *Operating system* : N/A
  - *Docker version* : 
```
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
### Additional context

```N/A```

**Comment by Xide** [comment]
Indeed, the documentation needs `virtualenv` to be installed on the control machine. 
Since it can be installed using pip, we could : 

- [ ] Add documentation on the requirements (python3 + pip versions) for CM
- [ ] Add a Makefile target to install virtualenv with pip, put it as a dependency of `doc`
