### ISSUE TITLE
Upload ROADMAP

### ISSUE THREAD

**Issue by guiadco** [actiniumio/allspark#45]
### Story
- as a User is want to see your Product Roadmap

---
### Motivation
Why is this feature needed ?

I want to see what is coming

---
### Acceptance criteria

N/A

---
### Implementation proposal

Upload the actual Product Roadmap

---
### Status

- [ ] Implementation

**Comment by davStar** [comment]
Hello guys

While we are realigning our software architecture and engineering processing with our internal CI. I propose we keep the community informed about the next deliverables. Of course the roadmap has been done several weeks ago. I m working to readapt it. Then I fully agree the next roadmap diagram (and others) must be compliant with our internal engineering  mechanism compliant with our CI/CD.

**Comment by davStar** [comment]
Of course to be discuss :)
